spring.application.name=Crm_Project

spring.datasource.url=jdbc:postgresql://localhost:5432/postgre_db?currentSchema=crm_project
spring.jpa.properties.hibernate.default_schema=crm_project
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION}

allowed.origins=http://localhost:3000